import { nanoid } from 'nanoid'
import type { Task } from "./kanban.types";

const t = () => nanoid(10)

export const initialTasks: Task[] = [
 	{
		id: t(),
		columnId: 'inprogress',
		title: 'Design user authentication flow',
		description:
			'Create wireframes and mockups for the login and registration pages',
		priority: 'high',
		assignee: 'John Doe',
		dueDate: '2024-01-15',
		project: 'Auth System',
		members: ['JD', 'JS', 'MJ'],
	},
	{
		id: t(),
		columnId: 'inprogress',
		title: 'Implement API endpoints',
		description: 'Set up RESTful API endpoints for user management',
		priority: 'medium',
		assignee: 'Jane Smith',
		dueDate: '2024-01-20',
		project: 'Backend API',
		members: ['JS', 'SW'],
	},
	{
		id: t(),
		columnId: 'inprogress',
		title: 'Write unit tests',
		description: 'Create comprehensive test coverage for all new features',
		priority: 'low',
		assignee: 'Mike Johnson',
		dueDate: '2024-01-25',
		project: 'QA Suite',
		members: ['MJ'],
	},
	{
		id: t(),
		columnId: 'inprogress',
		title: 'Setup CI/CD pipeline',
		description:
			'Configure GitHub Actions for automated testing and deployment',
		priority: 'high',
		assignee: 'Sarah Williams',
		dueDate: '2024-01-18',
		project: 'DevOps',
		members: ['SW', 'TB', 'AC'],
	},
	{
		id: t(),
		columnId: 'inprogress',
		title: 'Update documentation',
		description: 'Document new API endpoints and usage examples',
		priority: 'medium',
		assignee: 'Tom Brown',
		dueDate: '2024-01-22',
		project: 'Docs',
		members: ['TB'],
	},
  {
	id: t(),
    columnId: 'backlog',
    title: 'Migrate to React 19',
    description: 'Evaluar breaking changes y actualizar dependencias',
    priority: 'high',
    assignee: 'Alice Chen',
    dueDate: '2024-03-01',
  },
  {
	id: t(),
    columnId: 'backlog',
    title: 'Add dark mode support',
    description: 'Implementar tema oscuro con CSS variables',
    priority: 'medium',
    assignee: 'David Kim',
    dueDate: '2024-02-28',
  },
  {
	id: t(),
    columnId: 'backlog',
    title: 'Optimize bundle size',
    description: 'Analizar y reducir el tamaño del bundle final',
    priority: 'low',
    assignee: 'Elena Garcia',
    dueDate: '2024-03-10',
  },
  {
	id: t(),
    columnId: 'backlog',
    title: 'Integrate Sentry for error tracking',
    description: 'Configurar monitoreo de errores en producción',
    priority: 'medium',
    assignee: 'Carlos Mendez',
    dueDate: '2024-02-20',
  },
  {
	id: t(),
    columnId: 'backlog',
    title: 'Write E2E tests with Playwright',
    description: 'Cubrir flujos críticos del usuario',
    priority: 'high',
    assignee: 'Nina Patel',
    dueDate: '2024-03-05',
  },
  {
	id: t(),
    columnId: 'backlog',
    title: 'Add i18n support',
    description: 'Soporte para español e inglés',
    priority: 'medium',
    assignee: 'Luis Fernandez',
    dueDate: '2024-03-15',
  },
  {
	id: t(),
    columnId: 'backlog',
    title: 'Implement WebSocket notifications',
    description: 'Notificaciones en tiempo real para cambios',
    priority: 'low',
    assignee: 'Sophia Lee',
    dueDate: '2024-03-20',
  },
  {
	id: t(),
    columnId: 'backlog',
    title: 'Add keyboard shortcuts',
    description: 'Mejorar accesibilidad con atajos de teclado',
    priority: 'low',
    assignee: 'James Wilson',
    dueDate: '2024-04-01',
  },
  {
	id: t(),
    columnId: 'backlog',
    title: 'Create user onboarding tutorial',
    description: 'Tour guiado para nuevos usuarios',
    priority: 'medium',
    assignee: 'Olivia Brown',
    dueDate: '2024-03-25',
  },
  {
	id: t(),
    columnId: 'backlog',
    title: 'Implement rate limiting',
    description: 'Proteger endpoints públicos de abuso',
    priority: 'high',
    assignee: 'Robert Taylor',
    dueDate: '2024-02-15',
  },

  // TODO (10)
  {
	id: t(),
    columnId: 'todo',
    title: 'Design system component library',
    description: 'Crear Storybook con todos los componentes reusables',
    priority: 'high',
    assignee: 'Maria Lopez',
    dueDate: '2024-02-10',
  },
  {
	id: t(),
    columnId: 'todo',
    title: 'Implement forgot password flow',
    description: 'Recuperación de contraseña vía email',
    priority: 'high',
    assignee: 'John Doe',
    dueDate: '2024-02-05',
  },
  {
	id: t(),
    columnId: 'todo',
    title: 'Add drag-and-drop file upload',
    description: 'Subida de archivos con vista previa',
    priority: 'medium',
    assignee: 'Jane Smith',
    dueDate: '2024-02-12',
  },
  {
	id: t(),
    columnId: 'todo',
    title: 'Improve mobile responsiveness',
    description: 'Ajustar layouts para tablets y móviles',
    priority: 'medium',
    assignee: 'Mike Johnson',
    dueDate: '2024-02-18',
  },
  {
	id: t(),
    columnId: 'todo',
    title: 'Set up database indexes',
    description: 'Optimizar consultas lentas en PostgreSQL',
    priority: 'high',
    assignee: 'Sarah Williams',
    dueDate: '2024-01-30',
  },
  {
	id: t(),
    columnId: 'todo',
    title: 'Implement search functionality',
    description: 'Búsqueda global con filtros',
    priority: 'medium',
    assignee: 'Tom Brown',
    dueDate: '2024-02-20',
  },
  {
	id: t(),
    columnId: 'todo',
    title: 'Add export to CSV/PDF',
    description: 'Exportar reportes y tablas',
    priority: 'low',
    assignee: 'Alice Chen',
    dueDate: '2024-03-01',
  },
  {
	id: t(),
    columnId: 'todo',
    title: 'Create landing page',
    description: 'Página de marketing con características del producto',
    priority: 'medium',
    assignee: 'David Kim',
    dueDate: '2024-02-25',
  },
  {
	id: t(),
    columnId: 'todo',
    title: 'Set up staging environment',
    description: 'Entorno de pre-producción para testing',
    priority: 'high',
    assignee: 'Elena Garcia',
    dueDate: '2024-02-08',
  },
  {
	id: t(),
    columnId: 'todo',
    title: 'Implement OAuth2 (Google/GitHub)',
    description: 'Login social con proveedores externos',
    priority: 'high',
    assignee: 'Carlos Mendez',
    dueDate: '2024-02-14',
  },

  // INPROGRESS (10 más, aparte de las 5 originales)
  {
	id: t(),
    columnId: 'inprogress',
    title: 'Refactor API error handling',
    description: 'Estandarizar respuestas de error',
    priority: 'medium',
    assignee: 'Nina Patel',
    dueDate: '2024-01-28',
  },
  {
	id: t(),
    columnId: 'inprogress',
    title: 'Add logging service',
    description: 'Implementar Winston para logs estructurados',
    priority: 'low',
    assignee: 'Luis Fernandez',
    dueDate: '2024-01-29',
  },
  {
	id: t(),
    columnId: 'inprogress',
    title: 'Update user profile UI',
    description: 'Rediseñar página de perfil con nuevos campos',
    priority: 'medium',
    assignee: 'Sophia Lee',
    dueDate: '2024-01-27',
  },
  {
	id: t(),
    columnId: 'inprogress',
    title: 'Fix memory leak in dashboard',
    description: 'Investigar y corregir fuga de memoria',
    priority: 'high',
    assignee: 'James Wilson',
    dueDate: '2024-01-26',
  },
  {
	id: t(),
    columnId: 'inprogress',
    title: 'Implement caching with Redis',
    description: 'Cachear respuestas frecuentes',
    priority: 'high',
    assignee: 'Olivia Brown',
    dueDate: '2024-01-30',
  },

  // TEST (10)
  {
	id: t(),
    columnId: 'test',
    title: 'Test authentication flow',
    description: 'Validar login, registro y recuperación',
    priority: 'high',
    assignee: 'Robert Taylor',
    dueDate: '2024-01-25',
  },
  {
	id: t(),
    columnId: 'test',
    title: 'Test drag-and-drop stability',
    description: 'Asegurar que no haya bugs al mover tareas',
    priority: 'medium',
    assignee: 'Maria Lopez',
    dueDate: '2024-01-26',
  },
  {
	id: t(),
    columnId: 'test',
    title: 'Cross-browser testing',
    description: 'Chrome, Firefox, Safari, Edge',
    priority: 'medium',
    assignee: 'John Doe',
    dueDate: '2024-01-27',
  },
  {
	id: t(),
    columnId: 'test',
    title: 'Load testing API',
    description: 'Simular 1000 usuarios concurrentes',
    priority: 'high',
    assignee: 'Jane Smith',
    dueDate: '2024-01-28',
  },
  {
	id: t(),
    columnId: 'backlog',
    title: 'Security audit',
    description: 'Revisar vulnerabilidades comunes (XSS, CSRF)',
    priority: 'high',
    assignee: 'Mike Johnson',
    dueDate: '2024-01-29',
  },
  {
	id: t(),
    columnId: 'backlog',
    title: 'Test responsive layouts',
    description: 'Dispositivos: iPhone, iPad, Pixel, Galaxy',
    priority: 'low',
    assignee: 'Sarah Williams',
    dueDate: '2024-01-30',
  },
  {
	id: t(),
    columnId: 'backlog',
    title: 'Test notification system',
    description: 'Validar que lleguen emails y notificaciones',
    priority: 'medium',
    assignee: 'Tom Brown',
    dueDate: '2024-01-31',
  },
  {
	id: t(),
    columnId: 'done',
    title: 'Test file upload limits',
    description: 'Probar con archivos grandes y formatos inválidos',
    priority: 'low',
    assignee: 'Alice Chen',
    dueDate: '2024-02-01',
  },
  {
	id: t(),
    columnId: 'done',
    title: 'Test export features',
    description: 'Verificar CSV/PDF generados',
    priority: 'medium',
    assignee: 'David Kim',
    dueDate: '2024-02-02',
  },
  {
	id: t(),
    columnId: 'test',
    title: 'Test keyboard navigation',
    description: 'Accesibilidad con solo teclado',
    priority: 'low',
    assignee: 'Elena Garcia',
    dueDate: '2024-02-03',
  },

  // DONE (10)
  {
	id: t(),
    columnId: 'done',
    title: 'Set up project repository',
    description: 'GitHub con branch protection rules',
    priority: 'high',
    assignee: 'Carlos Mendez',
    dueDate: '2024-01-05',
  },
  {
	id: t(),
    columnId: 'done',
    title: 'Initial project setup (Vite + TS)',
    description: 'Configuración inicial del frontend',
    priority: 'high',
    assignee: 'Nina Patel',
    dueDate: '2024-01-06',
  },
  {
	id: t(),
    columnId: 'done',
    title: 'Design database schema',
    description: 'Modelado de usuarios, tareas, columnas',
    priority: 'high',
    assignee: 'Luis Fernandez',
    dueDate: '2024-01-07',
  },
  {
	id: t(),
    columnId: 'done',
    title: 'Create basic kanban board UI',
    description: 'Implementación inicial con drag & drop',
    priority: 'high',
    assignee: 'Sophia Lee',
    dueDate: '2024-01-10',
  },
  {
	id: t(),
    columnId: 'done',
    title: 'Add task modal form',
    description: 'Crear/editar tareas',
    priority: 'medium',
    assignee: 'James Wilson',
    dueDate: '2024-01-12',
  },
  {
	id: t(),
    columnId: 'done',
    title: 'Persist data in localStorage',
    description: 'Guardar tareas en el navegador',
    priority: 'medium',
    assignee: 'Olivia Brown',
    dueDate: '2024-01-14',
  },
  {
	id: t(),
    columnId: 'done',
    title: 'Add priority badges',
    description: 'Mostrar prioridad con colores',
    priority: 'low',
    assignee: 'Robert Taylor',
    dueDate: '2024-01-15',
  },
  {
	id: t(),
    columnId: 'done',
    title: 'Implement delete task',
    description: 'Botón para eliminar tareas',
    priority: 'medium',
    assignee: 'Maria Lopez',
    dueDate: '2024-01-16',
  },
  {
	id: t(),
    columnId: 'done',
    title: 'Add due date picker',
    description: 'Selector de fecha en el formulario',
    priority: 'low',
    assignee: 'John Doe',
    dueDate: '2024-01-17',
  },
  {
	id: t(),
    columnId: 'done',
    title: 'Create initial documentation',
    description: 'README con instrucciones de uso',
    priority: 'low',
    assignee: 'Jane Smith',
    dueDate: '2024-01-18',
  },

  // CANCELLED (5)
  {
	id: t(),
    columnId: 'cancelled',
    title: 'Integrate with Jira (deprecated)',
    description: 'Decidimos usar GitHub Projects en su lugar',
    priority: 'medium',
    assignee: 'Mike Johnson',
    dueDate: '2024-01-09',
  },
  {
	id: t(),
    columnId: 'cancelled',
    title: 'Blockchain-based verification',
    description: 'Overkill para el alcance actual',
    priority: 'high',
    assignee: 'Sarah Williams',
    dueDate: '2024-01-11',
  },
  {
	id: t(),
    columnId: 'cancelled',
    title: 'Native mobile app (iOS/Android)',
    description: 'Prioridad: web responsive primero',
    priority: 'low',
    assignee: 'Tom Brown',
    dueDate: '2024-01-13',
  },
  {
	id: t(),
    columnId: 'cancelled',
    title: 'Voice command support',
    description: 'No hay demanda de usuarios',
    priority: 'low',
    assignee: 'Alice Chen',
    dueDate: '2024-01-19',
  },
  {
	id: t(),
    columnId: 'cancelled',
    title: 'Augmented reality preview',
    description: 'Idea descartada por complejidad',
    priority: 'medium',
    assignee: 'David Kim',
    dueDate: '2024-01-21',
  },
];