export type NavItem = {
	type: 'item' | 'group' | 'link'
	id: string
	label: string
	icon: string
	path?: string
	auth?: string[]
	children?: NavItem[]
}

export const navigationMenu: NavItem[] = [
	{
		type: 'item',
		id: 'dashboard',
		label: 'Dashboard',
		icon: 'speedometer2',
		path: '#',
		auth: ['Administrador', 'Viewer'],
	},
	{
		type: 'group',
		id: 'gestor_ administrativo',
		label: 'Administrativo',
		path: '',
		icon: 'people',
		auth: ['Administrador'],
		children: [
			{
				type: 'item',
				id: 'manage-user',
				label: 'Administradores',
				icon: 'shield-lock',
				path: '#',
				auth: ['Administrador'],
			},
			{
				type: 'item',
				id: 'logs',
				label: 'Logs Administradores',
				icon: 'file-earmark-text',
				path: '#',
				auth: ['Administrador'],
			},
		],
	},
	{
		type: 'group',
		id: 'gestor_usuarios',
		label: 'Gestor de usuarios',
		path: '',
		icon: 'people',
		auth: ['Administrador', 'Agente', 'Viewer'],
		children: [
			{
				type: 'item',
				id: 'web-users',
				label: 'Usuarios',
				icon: 'people',
				path: '#',
				auth: ['Administrador', 'Agente', 'Viewer'],
			},
			{
				type: 'item',
				id: 'logs-users',
				label: 'Logs Usuarios',
				icon: 'file-text',
				path: '#',
				auth: ['Administrador', 'Agente'],
			},
		],
	},
	{
		type: 'group',
		path: '',
		id: 'gestor_contenido',
		label: 'Gestor de contenido',
		icon: 'folder',
		auth: ['Administrador'],
		children: [
			{
				path: '#',
				type: 'item',
				id: 'paises',
				label: 'Países',
				icon: 'globe',
				auth: ['Administrador'],
			},
			{
				path: '#',
				type: 'item',
				id: 'premios',
				label: 'Premios',
				icon: 'gift',
				auth: ['Administrador'],
			},
			{
				path: '#',
				type: 'item',
				id: 'terminos_y_condiciones',
				label: 'Términos y condiciones',
				icon: 'file-earmark-text',
				auth: ['Administrador'],
			},
			{
				path: '#',
				type: 'item',
				id: 'preguntas-frecuentes',
				label: 'Preguntas Frecuentes',
				icon: 'question-circle',
				auth: ['Administrador'],
			},
			{
				path: '#',
				type: 'item',
				id: 'categorias',
				label: 'Categorías',
				icon: 'tag',
				auth: ['Administrador'],
			},
			{
				path: '#',
				type: 'item',
				id: 'empresas',
				label: 'Empresas',
				icon: 'building',
				auth: ['Administrador'],
			},
			{
				path: '#',
				type: 'item',
				id: 'aceleradores',
				label: 'Aceleradores',
				icon: 'lightning-charge',
				auth: ['Administrador'],
			},
			{
				path: '#',
				type: 'item',
				id: 'productos',
				label: 'Productos',
				icon: 'box-seam',
				auth: ['Administrador'],
			},
			{
				path: '#',
				type: 'item',
				id: 'ruleta',
				label: 'Ruleta',
				icon: 'arrow-repeat',
				auth: ['Administrador'],
			},
			{
				type: 'item',
				id: 'winner-banner',
				label: 'Banner Ganadores',
				icon: 'award',
				auth: ['Administrador'],
				path: 'winner-banner',
			},
		],
	},
	{
		type: 'group',
		id: 'tickets_promo',
		label: 'Ordenes de compra',
		icon: 'list-check',
		auth: ['Administrador', 'Agente'],
		children: [
			{
				path: 'tickets/upload-order',
				type: 'item',
				id: 'upload-order',
				label: 'Subir Ordenes',
				icon: 'cloud-upload',
				auth: ['Administrador', 'Agente'],
			},
			{
				path: 'tickets/registered',
				type: 'item',
				id: 'registered-tickets',
				label: 'Ordenes Registrados',
				icon: 'card-list',
				auth: ['Administrador', 'Agente'],
			},
			{
				path: 'tickets/approved',
				type: 'item',
				id: 'approved-tickets',
				label: 'Ordenes Aprobados',
				icon: 'check-circle',
				auth: ['Administrador', 'Agente'],
			},
			{
				path: 'tickets/pending',
				type: 'item',
				id: 'pending-tickets',
				label: 'Ordenes Pendientes',
				icon: 'hourglass-split',
				auth: ['Administrador', 'Agente'],
			},
			{
				path: 'tickets/rejected',
				type: 'item',
				id: 'rejected-tickets',
				label: 'Ordenes Rechazados',
				icon: 'x-circle',
				auth: ['Administrador', 'Agente'],
			},
		],
	},
	{
		type: 'group',
		id: 'gestor_reportes',
		label: 'Gestor de reportes',
		icon: 'bar-chart',
		auth: ['Administrador', 'Agente'],
		children: [
			{
				path: 'report-management/ticket',
				type: 'item',
				id: 'ticket-reports',
				label: 'Ordenes de compra',
				icon: 'ticket',
				auth: ['Administrador', 'Agente'],
			},
		],
	},
	{
		type: 'item',
		id: 'campanas',
		label: 'Campañas de Email',
		icon: 'envelope-paper',
		path: '#',
		auth: ['Administrador'],
	},
	{
		type: 'item',
		id: 'campanas-whatsapp',
		label: 'Campañas de WhatsApp',
		icon: 'whatsapp',
		path: '#',
		auth: ['Administrador'],
	},
	{
		path: '#',
		type: 'item',
		id: 'banderas',
		label: 'Flags',
		icon: 'flag-fill',
		auth: ['Administrador'],
	},
]
