import {
	Calendar,
	CalendarDays,
	Component,
	CreditCard,
	Globe,
	Inbox,
	Loader,
	MessageSquare,
	PenSquare,
	StickyNote,
	Upload,
} from 'lucide-react'
import type { NavItem } from '@/types/navigation-menu'

export const exampleNavigation: NavItem[] = [
	{
		label: 'Example Components',
		path: '#',
		icon: Component,
		type: 'group',
		id: 'example-components',
		children: [
			{
				id: 'table',
				path: '/examples/table',
				label: 'Table',
				icon: CreditCard,
				type: 'item',
			},
			{
				id: 'date-picker',
				path: '/examples/date-picker',
				label: 'Date Picker',
				icon: CalendarDays,
				type: 'item',
			},
			{
				id: 'dropzone',
				path: '/examples/dropzone',
				label: 'Dropzone',
				icon: Upload,
				type: 'item',
			},
			{
				id: 'full-calendar',
				path: '/examples/full-calendar',
				label: 'Full Calendar',
				icon: Calendar,
				type: 'item',
			},
			{
				id: 'kanban',
				path: '/examples/kanban',
				label: 'Kanban Board',
				icon: PenSquare,
				type: 'item',
			},
			{
				id: 'editor',
				path: '/examples/editor',
				label: 'Editor',
				icon: PenSquare,
				type: 'item',
			},
			{
				id: 'chat',
				path: '/examples/chat',
				label: 'Chat',
				icon: MessageSquare,
				type: 'item',
			},
			{
				id: 'notes',
				path: '/examples/google-keep',
				label: 'Notes',
				icon: StickyNote,
				type: 'item',
			},
			{
				id: 'otp',
				path: '/examples/otp',
				label: 'OTP Input',
				icon: Globe,
				type: 'item',
			},
			{
				id: 'country-selector',
				path: '/examples/country-selector',
				label: 'Country Selector',
				icon: Globe,
				type: 'item',
			},
			{
				id: 'skeleton',
				path: '/examples/skeleton',
				label: 'Skeleton',
				icon: Loader,
				type: 'item',
			},
			{
				id: 'empty-state',
				path: '/examples/empty-state',
				label: 'Empty State',
				icon: Inbox,
				type: 'item',
			},
		],
	},
]
