import {
	Award,
	BarChart3,
	Building2,
	Calendar,
	CalendarDays,
	CheckCircle,
	ChevronDown,
	ChevronUp,
	ClipboardCheck,
	CreditCard,
	ExternalLink,
	FileText,
	Flag,
	Folder,
	FolderOpen,
	Gauge,
	Gift,
	Globe,
	HelpCircle,
	Hourglass,
	Image,
	ListChecks,
	Mail,
	MessageSquare,
	Package,
	PenSquare,
	RefreshCw,
	ShieldCheck,
	StickyNote,
	Tag,
	Ticket,
	Upload,
	Users,
	XCircle,
	Zap,
} from 'lucide-react'

export const iconMap: Record<
	string,
	React.ComponentType<{
		size?: number
		className?: string
		'aria-label'?: string
	}>
> = {
	speedometer2: Gauge,
	people: Users,
	'shield-lock': ShieldCheck,
	'file-earmark-text': FileText,
	'file-text': FileText,
	folder: Folder,
	'folder-open': FolderOpen,
	globe: Globe,
	gift: Gift,
	'question-circle': HelpCircle,
	tag: Tag,
	building: Building2,
	'lightning-charge': Zap,
	'box-seam': Package,
	'arrow-repeat': RefreshCw,
	award: Award,
	'list-check': ListChecks,
	'cloud-upload': Upload,
	'card-list': CreditCard,
	'check-circle': CheckCircle,
	'clipboard-check': ClipboardCheck,
	'hourglass-split': Hourglass,
	'x-circle': XCircle,
	'bar-chart': BarChart3,
	ticket: Ticket,
	'envelope-paper': Mail,
	whatsapp: ExternalLink,
	'flag-fill': Flag,
	'chevron-up': ChevronUp,
	'chevron-down': ChevronDown,
	calendar: Calendar,
	'calendar-days': CalendarDays,
	'pen-square': PenSquare,
	'message-square': MessageSquare,
	'sticky-note': StickyNote,
	image: Image,
}
